package org.shirakawatyu.yamibo.novel.util

data class AppStrings(
    val settings: String,
    val blacklist: String,
    val feedback: String,
    val checkUpdate: String,
    val close: String,
    val clearCache: String,
    val confirm: String,
    val cancel: String,
    val autoSignIn: String,
    val autoSignInDesc: String,
    val autoVersionUpdate: String,
    val autoVersionUpdateDesc: String,
    val autoClearCache: String,
    val autoClearCacheDesc: String,
    val darkMode: String,
    val darkModeDesc: String,
    val networkOptimization: String,
    val networkOptimizationDesc: String,
    val blockPosts: String,
    val blockPostsDesc: String,
    val language: String,
    val languageDesc: String,
    val clearCacheConfirmText: String,
    val checkingUpdate: String,
    val noNewVersion: String,
    val backup: String,
    val backupDialogText: String,
    val exportBackup: String,
    val importBackup: String,
    val backupExported: String,
    val backupFailed: String,
    val importConfirmTitle: String,
    val importConfirmText: String,
    val importDoneTitle: String,
    val importDoneText: String,
    val restartNow: String,
) {
    companion object {
        fun forMode(mode: String): AppStrings {
            return if (LanguageModeUtil.normalize(mode) == LanguageModeUtil.TRADITIONAL)
                TRADITIONAL else SIMPLIFIED
        }

        private val SIMPLIFIED = AppStrings(
            settings = "设置",
            blacklist = "黑名单",
            feedback = "反馈",
            checkUpdate = "更新",
            close = "关闭",
            clearCache = "清理缓存",
            confirm = "确定",
            cancel = "取消",
            autoSignIn = "自动签到",
            autoSignInDesc = "启动或返回应用时自动签到",
            autoVersionUpdate = "自动版本更新",
            autoVersionUpdateDesc = "软件启动时自动检查新版本",
            autoClearCache = "自动清理缓存",
            autoClearCacheDesc = "每 %d 天清理一次",
            darkMode = "暗黑模式",
            darkModeDesc = "使用经典黑蓝界面",
            networkOptimization = "网络优化",
            networkOptimizationDesc = "使用优化后的 DNS 连接论坛",
            blockPosts = "屏蔽帖子",
            blockPostsDesc = "在论坛列表和帖子页显示屏蔽按钮",
            language = "繁體中文",
            languageDesc = "使用繁体，修改论坛默认语言",
            clearCacheConfirmText = "确定要清理小说页面和漫画图片缓存吗？此操作不可撤销。",
            checkingUpdate = "正在检查更新…",
            noNewVersion = "未发现新版本，当前安装版本：v%s",
            backup = "备份",
            backupDialogText = "备份包含：收藏与排序、漫画目录、阅读进度、浏览历史、黑名单和全部设置。不包含小说页面与漫画图片缓存；恢复后可能需要重新登录论坛。",
            exportBackup = "导出备份",
            importBackup = "导入备份",
            backupExported = "备份已导出",
            backupFailed = "操作失败：%s",
            importConfirmTitle = "导入备份",
            importConfirmText = "导入将覆盖本机现有的收藏、目录、历史、黑名单和设置，且无法撤销。确定继续吗？",
            importDoneTitle = "导入成功",
            importDoneText = "备份已恢复，需要重启应用生效。",
            restartNow = "立即重启",
        )

        private val TRADITIONAL = AppStrings(
            settings = "設定",
            blacklist = "黑名單",
            feedback = "反饋",
            checkUpdate = "更新",
            close = "關閉",
            clearCache = "清理緩存",
            confirm = "確定",
            cancel = "取消",
            autoSignIn = "自動簽到",
            autoSignInDesc = "啟動或返回應用時自動簽到",
            autoVersionUpdate = "自動版本更新",
            autoVersionUpdateDesc = "軟體啟動時自動檢查新版本",
            autoClearCache = "自動清理緩存",
            autoClearCacheDesc = "每 %d 天清理一次",
            darkMode = "暗黑模式",
            darkModeDesc = "使用經典黑藍界面",
            networkOptimization = "網路優化",
            networkOptimizationDesc = "使用優化後的 DNS 連接論壇",
            blockPosts = "屏蔽帖子",
            blockPostsDesc = "在論壇列表和帖子頁顯示屏蔽按鈕",
            language = "繁體中文",
            languageDesc = "使用繁體，修改論壇預設語言",
            clearCacheConfirmText = "確定要清理小說頁面和漫畫圖片緩存嗎？此操作不可撤銷。",
            checkingUpdate = "正在檢查更新…",
            noNewVersion = "未發現新版本，目前安裝版本：v%s",
            backup = "備份",
            backupDialogText = "備份包含：收藏與排序、漫畫目錄、閱讀進度、瀏覽歷史、黑名單和全部設定。不包含小說頁面與漫畫圖片緩存；恢復後可能需要重新登入論壇。",
            exportBackup = "導出備份",
            importBackup = "導入備份",
            backupExported = "備份已導出",
            backupFailed = "操作失敗：%s",
            importConfirmTitle = "導入備份",
            importConfirmText = "導入將覆蓋本機現有的收藏、目錄、歷史、黑名單和設定，且無法撤銷。確定繼續嗎？",
            importDoneTitle = "導入成功",
            importDoneText = "備份已恢復，需要重啟應用生效。",
            restartNow = "立即重啟",
        )
    }
}
