package org.shirakawatyu.yamibo.novel.util

data class AppStrings(
    val settings: String,
    val blacklist: String,
    val feedback: String,
    val checkUpdate: String,
    val close: String,
    val clearCache: String,
    val confirm: String,
    val cancel: String,
    val autoSignIn: String,
    val autoSignInDesc: String,
    val autoVersionUpdate: String,
    val autoVersionUpdateDesc: String,
    val autoClearCache: String,
    val autoClearCacheDesc: String,
    val darkMode: String,
    val darkModeDesc: String,
    val networkOptimization: String,
    val networkOptimizationDesc: String,
    val blockPosts: String,
    val blockPostsDesc: String,
    val language: String,
    val languageDesc: String,
    val clearCacheConfirmText: String,
    val checkingUpdate: String,
    val noNewVersion: String,
) {
    companion object {
        fun forMode(mode: String): AppStrings {
            return if (LanguageModeUtil.normalize(mode) == LanguageModeUtil.TRADITIONAL)
                TRADITIONAL else SIMPLIFIED
        }

        private val SIMPLIFIED = AppStrings(
            settings = "设置",
            blacklist = "黑名单",
            feedback = "反馈",
            checkUpdate = "检查更新",
            close = "关闭",
            clearCache = "清理缓存",
            confirm = "确定",
            cancel = "取消",
            autoSignIn = "自动签到",
            autoSignInDesc = "启动或返回应用时自动签到",
            autoVersionUpdate = "自动版本更新",
            autoVersionUpdateDesc = "软件启动时自动检查新版本",
            autoClearCache = "自动清理缓存",
            autoClearCacheDesc = "每 %d 天清理一次",
            darkMode = "暗黑模式",
            darkModeDesc = "使用经典黑蓝界面",
            networkOptimization = "网络优化",
            networkOptimizationDesc = "使用优化后的 DNS 连接论坛",
            blockPosts = "屏蔽帖子",
            blockPostsDesc = "在论坛列表和帖子页显示屏蔽按钮",
            language = "繁體中文",
            languageDesc = "默认简体，打开后使用繁體，并影响论坛 BBS 默认语言",
            clearCacheConfirmText = "确定要清理小说页面和漫画图片缓存吗？此操作不可撤销。",
            checkingUpdate = "正在检查更新…",
            noNewVersion = "未发现新版本，当前安装版本：v%s",
        )

        private val TRADITIONAL = AppStrings(
            settings = "設定",
            blacklist = "黑名單",
            feedback = "反饋",
            checkUpdate = "檢查更新",
            close = "關閉",
            clearCache = "清理緩存",
            confirm = "確定",
            cancel = "取消",
            autoSignIn = "自動簽到",
            autoSignInDesc = "啟動或返回應用時自動簽到",
            autoVersionUpdate = "自動版本更新",
            autoVersionUpdateDesc = "軟體啟動時自動檢查新版本",
            autoClearCache = "自動清理緩存",
            autoClearCacheDesc = "每 %d 天清理一次",
            darkMode = "暗黑模式",
            darkModeDesc = "使用經典黑藍界面",
            networkOptimization = "網路優化",
            networkOptimizationDesc = "使用優化後的 DNS 連接論壇",
            blockPosts = "屏蔽帖子",
            blockPostsDesc = "在論壇列表和帖子頁顯示屏蔽按鈕",
            language = "繁體中文",
            languageDesc = "預設簡體，打開後使用繁體，並影響論壇 BBS 預設語言",
            clearCacheConfirmText = "確定要清理小說頁面和漫畫圖片緩存嗎？此操作不可撤銷。",
            checkingUpdate = "正在檢查更新…",
            noNewVersion = "未發現新版本，目前安裝版本：v%s",
        )
    }
}
