package org.shirakawatyu.yamibo.novel.util

data class AppStrings(
    val settings: String,
    val blacklist: String,
    val feedback: String,
    val checkUpdate: String,
    val close: String,
    val clearCache: String,
    val confirm: String,
    val cancel: String,
    val manualDownload: String,
    val later: String,
    val downloadAndInstall: String,
    val downloading: String,
    val reopenInstaller: String,
    val retryAutoUpdate: String,
    val openDownloadPage: String,
    val autoCheckUpdateFailed: String,
    val newVersionFound: String,
    val autoSignIn: String,
    val autoSignInDesc: String,
    val autoVersionUpdate: String,
    val autoVersionUpdateDesc: String,
    val autoClearCache: String,
    val autoClearCacheDesc: String,
    val darkMode: String,
    val darkModeDesc: String,
    val networkOptimization: String,
    val networkOptimizationDesc: String,
    val blockPosts: String,
    val blockPostsDesc: String,
    val language: String,
    val languageDesc: String,
    val clearCacheConfirmTitle: String,
    val clearCacheConfirmText: String,
    val clearingCache: String,
    val cacheCleared: String,
    val noFavorites: String,
    val noMatchingFavorites: String,
    val searchHint: String,
    val manage: String,
    val done: String,
    val selectAll: String,
    val delete: String,
    val pin: String,
    val unpin: String,
    val checkUpdateNow: String,
    val checkingUpdate: String,
    val noNewVersion: String,
    val hide: String,
    val unhide: String,
    val loginRequired: String,
    val loginPrompt: String,
    val pinTop: String,
    val unpinTop: String,
) {
    companion object {
        fun forMode(mode: String): AppStrings {
            return if (LanguageModeUtil.normalize(mode) == LanguageModeUtil.TRADITIONAL)
                TRADITIONAL else SIMPLIFIED
        }

        private val SIMPLIFIED = AppStrings(
            settings = "设置",
            blacklist = "黑名单",
            feedback = "反馈",
            checkUpdate = "检查更新",
            close = "关闭",
            clearCache = "清理缓存",
            confirm = "确定",
            cancel = "取消",
            manualDownload = "手动下载",
            later = "稍后",
            downloadAndInstall = "下载并安装",
            downloading = "下载中",
            reopenInstaller = "重新打开安装器",
            retryAutoUpdate = "重试自动更新",
            openDownloadPage = "打开下载页",
            autoCheckUpdateFailed = "自动检查更新失败",
            newVersionFound = "发现新版本",
            autoSignIn = "自动签到",
            autoSignInDesc = "启动或返回应用时自动签到",
            autoVersionUpdate = "自动版本更新",
            autoVersionUpdateDesc = "软件启动时自动检查新版本",
            autoClearCache = "自动清理缓存",
            autoClearCacheDesc = "每 %d 天清理一次",
            darkMode = "暗黑模式",
            darkModeDesc = "使用经典黑蓝界面",
            networkOptimization = "网络优化",
            networkOptimizationDesc = "使用优化后的 DNS 连接论坛",
            blockPosts = "屏蔽帖子",
            blockPostsDesc = "在论坛列表和帖子页显示屏蔽按钮",
            language = "语言",
            languageDesc = "切换论坛和界面的显示语言",
            clearCacheConfirmTitle = "清理缓存",
            clearCacheConfirmText = "确定要清理小说页面和漫画图片缓存吗？此操作不可撤销。",
            clearingCache = "正在清理…",
            cacheCleared = "缓存已清理",
            noFavorites = "暂无收藏",
            noMatchingFavorites = "没有匹配的收藏",
            searchHint = "搜索收藏",
            manage = "管理",
            done = "完成",
            selectAll = "全选",
            delete = "删除",
            pin = "置顶",
            unpin = "取消置顶",
            checkUpdateNow = "检查更新",
            checkingUpdate = "正在检查更新…",
            noNewVersion = "未发现新版本，当前安装版本：v%s",
            hide = "隐藏",
            unhide = "取消隐藏",
            loginRequired = "需要登录",
            loginPrompt = "请在个人中心页面点击头像登录",
            pinTop = "置顶",
            unpinTop = "取消置顶",
        )

        private val TRADITIONAL = AppStrings(
            settings = "設定",
            blacklist = "黑名單",
            feedback = "反饋",
            checkUpdate = "檢查更新",
            close = "關閉",
            clearCache = "清理緩存",
            confirm = "確定",
            cancel = "取消",
            manualDownload = "手動下載",
            later = "稍後",
            downloadAndInstall = "下載並安裝",
            downloading = "下載中",
            reopenInstaller = "重新打開安裝器",
            retryAutoUpdate = "重試自動更新",
            openDownloadPage = "打開下載頁",
            autoCheckUpdateFailed = "自動檢查更新失敗",
            newVersionFound = "發現新版本",
            autoSignIn = "自動簽到",
            autoSignInDesc = "啟動或返回應用時自動簽到",
            autoVersionUpdate = "自動版本更新",
            autoVersionUpdateDesc = "軟體啟動時自動檢查新版本",
            autoClearCache = "自動清理緩存",
            autoClearCacheDesc = "每 %d 天清理一次",
            darkMode = "暗黑模式",
            darkModeDesc = "使用經典黑藍界面",
            networkOptimization = "網路優化",
            networkOptimizationDesc = "使用優化後的 DNS 連接論壇",
            blockPosts = "屏蔽帖子",
            blockPostsDesc = "在論壇列表和帖子頁顯示屏蔽按鈕",
            language = "語言",
            languageDesc = "切換論壇和介面的顯示語言",
            clearCacheConfirmTitle = "清理緩存",
            clearCacheConfirmText = "確定要清理小說頁面和漫畫圖片緩存嗎？此操作不可撤銷。",
            clearingCache = "正在清理…",
            cacheCleared = "緩存已清理",
            noFavorites = "暫無收藏",
            noMatchingFavorites = "沒有匹配的收藏",
            searchHint = "搜索收藏",
            manage = "管理",
            done = "完成",
            selectAll = "全選",
            delete = "刪除",
            pin = "置頂",
            unpin = "取消置頂",
            checkUpdateNow = "檢查更新",
            checkingUpdate = "正在檢查更新…",
            noNewVersion = "未發現新版本，目前安裝版本：v%s",
            hide = "隱藏",
            unhide = "取消隱藏",
            loginRequired = "需要登入",
            loginPrompt = "請在個人中心頁面點擊頭像登入",
            pinTop = "置頂",
            unpinTop = "取消置頂",
        )
    }
}
