package org.shirakawatyu.yamibo.novel.util.theme

val DARK_MODE_CSS_RULES_CLASSIC = listOf(
    "/* === CSS 鍙橀噺瑕嗙洊 === */",
    "body {",
    "--dz-BG-body: #0d141d !important;",
    "--dz-BG-0: #182332 !important;",
    "--dz-BG-5: #1f2c3d !important;",
    "--dz-BG-6: #3c5677 !important;",
    "--dz-FC-fff: #edf4fb !important;",
    "--dz-FC-333: #c7d8ea !important;",
    "--dz-FC-666: #acbed1 !important;",
    "--dz-FC-999: #8099b2 !important;",
    "--dz-FC-ccc: #95acc4 !important;",
    "--dz-FC-aaa: #6f89a3 !important;",
    "--dz-BOR-ed: #274766 !important;",
    "--dz-FC-color: #c7d8ea !important;",
    "}",
    "/* === 椤甸潰鏍硅儗鏅?=== */",
    "html, body { background: #0d141d !important; }",
    "/* === Desktop Discuz shell === */",
    "#toptb, #hd, #hd .hdc, #nv, #mu, #pt, #ct, #wp, #ft { background: #0d141d !important; border-color: #274766 !important; }",
    "#toptb, #toptb a, #hd, #hd a, #nv, #nv a, #mu, #mu a, #pt, #pt a, #ft, #ft a { color: #c7d8ea !important; }",
    "#nv, #nv ul, #nv li, #nv li a { background: #121b27 !important; border-color: #274766 !important; }",
    "#nv li.a, #nv li.a a, #nv li a:hover { background: #274766 !important; color: #ffffff !important; }",
    "#qmenu, #qmenu_menu, #visitedforums_menu, #fjump_menu { background: #182332 !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    "/* === 涓诲鍣?=== */",
    ".wp, #wp, .content, .main, .wrapper { background: #0d141d !important; }",
    "/* === 椤堕儴瀵艰埅鏍?=== */",
    ".header { background: #121b27 !important; border-color: #274766 !important; }",
    ".header, .header h2, .header h2 a, .header a { color: #edf4fb !important; }",
    ".header_toplogo { background: #121b27 !important; }",
    ".header_toplogo p { color: #edf4fb !important; }",
    "/* === 椤堕儴鏇村鑿滃崟 (鍙湅妤间富/鍊掑簭/杩斿洖棣栭〉/鐢佃剳鐗? === */",
    "#nav-more-menu { background: #182332 !important; }",
    ".nav-more-item { color: #c7d8ea !important; }",
    ".nav-more-item-text { color: #c7d8ea !important; }",
    ".nav-more-item svg { fill: #c7d8ea !important; color: #c7d8ea !important; }",
    "/* === 瀵艰埅鏍囩 (鍙湅浠?鍊掑簭/闃呰妯″紡绛? === */",
    ".sq_nav, .thread_nav, .sq_nav ul, .thread_nav ul { background: #121b27 !important; }",
    ".sq_nav a, .thread_nav a { color: #acbed1 !important; }",
    ".sq_nav .a a, .thread_nav .a a, .sq_nav a.active, .thread_nav a.active { color: #fff !important; background: #274766 !important; }",
    "/* === 鐗堝潡瀵艰埅 .z (鍒嗗尯/鏍囩) === */",
    ".z, .vertical_tab { background: #121b27 !important; }",
    ".z a, .vertical_tab a { color: #acbed1 !important; }",
    ".z .a, .vertical_tab .a, .z a.active, .vertical_tab a.active { color: #ffffff !important; background: #274766 !important; }",
    ".plc .z, .plc .flex-2, .plc .xg1, .plc .xw1 { background: #182332 !important; }",
    "/* === 鐗堝潡椤堕儴淇℃伅鏍?=== */",
    ".forumdisplay-top { background: #182332 !important; }",
    ".forumdisplay-top h2, .forumdisplay-top h2 a { color: #edf4fb !important; }",
    ".forumdisplay-top p, .forumdisplay-top p span { color: #acbed1 !important; }",
    "/* === 鎺掑簭鏍囩瀵艰埅 (鍏ㄩ儴/鏈€鏂?鐑棬/鏂板笘/绮惧崕) === */",
    ".dhnav_box, #dhnav, #dhnav_li { background: #121b27 !important; }",
    ".dhnav_box a, #dhnav a { color: #acbed1 !important; }",
    ".dhnav_box .mon a, #dhnav .mon a { color: #ffffff !important; }",
    ".tabs a.mon, .dhnv a.mon, #dhnav_li li.mon { border-bottom-color: #666666 !important; }",
    ".dhnavs_box, #dhnavs { background: #121b27 !important; }",
    "#dhnavs .swiper-slide a { color: #acbed1 !important; }",
    "#dhnavs .swiper-slide.mon, #dhnavs .swiper-slide.active, #dhnavs .swiper-slide[aria-selected=\"true\"] { background-color: #274766 !important; border-radius: 999px !important; box-shadow: inset 0 -3px #4ea1ff !important; }",
    "#dhnavs .swiper-slide.mon a, #dhnavs .swiper-slide.active a, #dhnavs .swiper-slide[aria-selected=\"true\"] a { color: #ffffff !important; font-weight: 700 !important; }",
    ".dhnav_box .mon, #dhnav .mon, #dhnav_li li.mon, .tabs a.mon, .dhnv a.mon { background-color: #274766 !important; color: #ffffff !important; border-bottom-color: #4ea1ff !important; }",
    "/* === 璁哄潧鍒楄〃瀹瑰櫒 === */",
    ".forumlist, .forumlist > div, .forumlist .mlist1 { background: #0d141d !important; }",
    ".forumlist .subforumshow { background: #121b27 !important; }",
    "/* === 鍒嗗尯鏍囬鏍?=== */",
    ".subforumshow { background: #121b27 !important; border-color: #274766 !important; }",
    ".subforumshow h2 a { color: #c7d8ea !important; }",
    ".subforumshow i { color: #8099b2 !important; }",
    ".subforumshow { color: #acbed1 !important; }",
    ".murl .mtit, .sub-forum .murl .mtit { color: #c7d8ea !important; }",
    "/* === 鐗堝潡鍒楄〃椤?(鍚唴閮?a 鏍囩鑳屾櫙瑕嗙洊) === */",
    ".mlist1, .mlist1 ul, .mlist1 li, .mlist1 li a, .mlist1 li span { background: #182332 !important; }",
    ".mlist1 li { border-color: #223247 !important; }",
    ".mlist1 .mtit { color: #edf4fb !important; }",
    ".mlist1 .mtxt { color: #95acc4 !important; }",
    ".mlist1 .mnum { color: #6f89a3 !important; }",
    "/* === 閫氱敤鏉垮潡瀹瑰櫒 (Discuz 妯℃澘) === */",
    ".bm, .bm_c, .bm_h { background: #182332 !important; border-color: #274766 !important; }",
    ".bm_h, .bm_h h2, .bm_h a { color: #c7d8ea !important; }",
    "/* === 甯栧瓙鍒楄〃 === */",
    ".tl_bm, .tl_bm ul, .tl_bm li, .tl_bm li a { background: #182332 !important; }",
    ".threadlist { background: #121b27 !important; }",
    ".threadlist li, .threadlist li a { background: #182332 !important; }",
    ".tl_bm li, .threadlist li { border-color: #223247 !important; }",
    ".tl_bm a, .threadlist a { color: #c7d8ea !important; }",
    "/* === Desktop forum display === */",
    ".pg_forumdisplay #ct, .pg_forumdisplay #threadlist, .pg_forumdisplay .tl, .pg_forumdisplay .tl table, .pg_forumdisplay .tl tbody { background: #0d141d !important; border-color: #274766 !important; }",
    ".pg_forumdisplay #threadlist .bm, .pg_forumdisplay #threadlist .bm_c, .pg_forumdisplay .tl th, .pg_forumdisplay .tl td { background: #182332 !important; border-color: #274766 !important; }",
    ".pg_forumdisplay .tl .th, .pg_forumdisplay .tl .ts th, .pg_forumdisplay .tl .ts td, .pg_forumdisplay #forumnewshow, .pg_forumdisplay #hiddenthread { background: #121b27 !important; color: #c7d8ea !important; border-color: #274766 !important; }",
    ".pg_forumdisplay .tl tr:hover th, .pg_forumdisplay .tl tr:hover td, .pg_forumdisplay .tl .threadpre td, .pg_forumdisplay .tl .threadpre:hover td { background: #1f2c3d !important; }",
    ".pg_forumdisplay .tl a, .pg_forumdisplay .ttp a, .pg_forumdisplay .ttp strong, .pg_forumdisplay .tps a { color: #7dbdf2 !important; }",
    ".pg_forumdisplay .ttp a, .pg_forumdisplay .ttp strong, .pg_forumdisplay .subtsm, .pg_forumdisplay .pop_moremenu li { background: #1f2c3d !important; border-color: #3c5677 !important; }",
    ".pg_forumdisplay .ttp .a a, .pg_forumdisplay .pop_moremenu a.xw1 { background: #274766 !important; color: #ffffff !important; border-color: #4ea1ff !important; }",
    ".pg_forumdisplay #autopbn, .pg_forumdisplay .pgbtn a, .pg_forumdisplay a.icon_up, .pg_forumdisplay #vfastpost { background: #1f2c3d !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    ".pg_forumdisplay .pg label, .pg_forumdisplay #typeid_fast_ctrl { background: #223247 !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    ".pg_forumdisplay #fastpostform .tedt, .pg_forumdisplay #fastpostform .tedt .bar, .pg_forumdisplay #fastpostform .tedt .area, .pg_forumdisplay #fastpostform label { background: #182332 !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    ".pg_forumdisplay #vfastpost #vf_b button { background: #274766 !important; color: #ffffff !important; border-color: #4b6a8f !important; text-shadow: none !important; }",
    ".pg_forumdisplay .tl th, .pg_forumdisplay .tl td, .pg_forumdisplay .tl .th, .pg_forumdisplay .tl .threadpre .threadpretd, .pg_forumdisplay .subtsm, .pg_forumdisplay #autopbn, .pg_forumdisplay a.icon_up { border-color: #274766 !important; }",
    "/* === 甯栧瓙璇︽儏 - 鏍囬 === */",
    ".view_tit, .view_tit h1, .view_tit a, .view_tit em { background: #182332 !important; color: #edf4fb !important; }",
    "/* === 甯栧瓙璇︽儏 - 妤间富淇℃伅鏍?=== */",
    "/* .pbr2/.pbg2 是用户侧栏的经验/积分彩条及轨道，排除以保持原色 */",
    ".pls, .pls div:not(.pbr2):not(.pbg2), .pls a { background: #121b27 !important; }",
    ".pls, .pls a, .pls em, .pls span { color: #c7d8ea !important; }",
    ".pls .pbg2 { background: rgba(255,255,255,0.10) !important; }",
    "/* === 甯栧瓙璇︽儏 - 甯栧瓙鍐呭瀹瑰櫒 === */",
    "/* .pbr/.pbg 是投票结果彩条及其轨道，颜色来自内联样式，必须排除以保持原色 */",
    ".plc, .plm, .plc div:not(.pbr):not(.pbg), .plm div:not(.pbr):not(.pbg) { background: #182332 !important; }",
    "/* === 甯栧瓙璇︽儏 - 浣滆€呰 === */",
    ".authi, .authi em, .authi a, .authi span { color: #acbed1 !important; }",
    "/* === 甯栧瓙璇︽儏 - 鏂囨湰棰滆壊 === */",
    ".message, .postmessage, .t_f, .t_msgfont, .message div, .t_f div { color: #c7d8ea !important; }",
    "/* === 甯栧瓙涓殑閾炬帴 === */",
    ".message a, .postmessage a, .t_f a, .t_msgfont a { color: #7dbdf2 !important; }",
    "/* === 鍒嗛〉瀵艰埅 === */",
    ".pgs, .pgs a, .pg, .pg a { background: #1f2c3d !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    ".page { background: #0d141d !important; }",
    ".page a { background: #1f2c3d !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    ".pgs .pg strong, .pg strong, .page strong { background: #3c5677 !important; color: #fff !important; }",
    "/* === Discuz 棰滆壊宸ュ叿绫?=== */",
    ".xi1 { color: #edf4fb !important; }",
    ".xi2 { color: #c7d8ea !important; }",
    ".xg1, .xg1 a { color: #acbed1 !important; }",
    ".xg2, .xg2 a { color: #95acc4 !important; }",
    "/* === 甯栧瓙鍏冧俊鎭?=== */",
    ".num, .views, .replies { color: #8099b2 !important; }",
    ".ts, .time { color: #6f89a3 !important; }",
    ".pipe { color: #3c5677 !important; }",
    "/* === 閿?鍥剧珷/鍥炬爣 === */",
    ".lock, .closed, .icn, .attach, .tattl { color: #8099b2 !important; }",
    "/* === 寮圭獥/瀵硅瘽妗?=== */",
    ".dialog, .ui-dialog, .bootstrap-dialog, .pop, .p_pop, .p_pop div { background: #182332 !important; color: #c7d8ea !important; }",
    ".dialog a, .ui-dialog a, .p_pop a { color: #c7d8ea !important; }",
    "/* === 搴曢儴鍥炲鏍?=== */",
    ".foot_reply, .f_c, .foot, #f_c { background: #182332 !important; border-color: #274766 !important; }",
    ".foot_reply a, .f_c a, .foot a { color: #c7d8ea !important; }",
    ".viewt-reply, .viewt-reply a { background: #274766 !important; color: #fff !important; }",
    ".fico-launch, .dm-star, .fico-reply, .fico-favorite, .fico-share, .fico { color: #c7d8ea !important; }",
    "/* === 涓汉涓績瀵艰埅 === */",
    ".my, .my a, .my i, .my span { color: #c7d8ea !important; }",
    ".mz, .mz a, .mz i, .mz span { color: #acbed1 !important; }",
    "/* === 涓汉涓績鍔熻兘鍒楄〃 (鍚唴閮?a 鏍囩鑳屾櫙瑕嗙洊) === */",
    ".myinfo_list_ico, .myinfo_list_ico ul { background: #182332 !important; }",
    ".myinfo_list_ico li  { background: #182332 !important; }",
    ".myinfo_list_ico li a { background: #121b27 !important; }",
    ".myinfo_list_ico li { border-color: #223247 !important; }",
    ".myinfo_list_ico li a { color: #c7d8ea !important; }",
    ".myinfo_list_ico li i { color: #edf4fb !important; }",
    "/* === 涓汉涓績鍏朵粬鍖哄潡 === */",
    ".myinfo, .myinfo_menu, .profile_section, .profile_section a { background: #182332 !important; }",
    ".myinfo a, .myinfo_menu a { color: #c7d8ea !important; }",
    ".myinfo_list, .myinfo_list li { border-color: #223247 !important; }",
    ".myinfo_list li span { color: #acbed1 !important; }",
    ".myinfo_list b { color: #c7d8ea !important; }",
    ".mtag, .profile_tag { color: #8099b2 !important; }",
    "/* === 琛ㄦ牸 === */",
    "table, tbody, td, th, .t_table, .t_table td, .t_table th { background: #182332 !important; color: #c7d8ea !important; border-color: #223247 !important; }",
    "/* === 椤佃剼 === */",
    ".footer, #footer { background: #121b27 !important; color: #8099b2 !important; border-color: #274766 !important; }",
    ".footer a, #footer a { color: #8099b2 !important; }",
    ".footer-nv, .footer-nv a, .footer-copy, .footer-copy a { background: #121b27 !important; color: #8099b2 !important; }",
    ".footer .mon { color: #8099b2 !important; }",
    "/* === input/select 鎺т欢 === */",
    "input, select, textarea { background: #223247 !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    "/* === 寮曠敤/浠ｇ爜鍧?=== */",
    "blockquote, .quote, .blockcode { background: #1f2c3d !important; border-color: #3c5677 !important; color: #acbed1 !important; }",
    "/* === 鍒嗗壊绾?=== */",
    "hr, .line, .partition { border-color: #274766 !important; }",
    "/* === 閫氱煡/鎻愮ず鏉?=== */",
    ".notice, .tip, .alert, .warning, .tips { background: #1f2c3d !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    "/* === 澶村儚杈规閫傞厤 === */",
    ".avatar img, .avatar, .my_avatar img { border-color: #274766 !important; }",
    "/* === 鎸夐挳閫氱敤 === */",
    ".btn, .button, button, .pn, .pnc, .mbtn { background: #274766 !important; color: #c7d8ea !important; border-color: #4b6a8f !important; }",
    "/* === 蹇€熷洖澶嶆 === */",
    "#postform, #fastpostform, .area textarea { background: #182332 !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    "/* === 鐐硅瘎/璇勫垎鏍囬 === */",
    ".psth { background: #121b27 !important; color: #c7d8ea !important; border-color: #274766 !important; }",
    ".psth .icon_ring { color: #8099b2 !important; }",
    "/* === 鐩綍/绔犺妭鎶樺彔鍒楄〃 === */",
    ".showcollapse_box { background: #182332 !important; border-color: #223247 !important; }",
    ".showcollapse_title { background: #1f2c3d !important; color: #c7d8ea !important; border-color: #274766 !important; }",
    ".showcollapse_content { background: #182332 !important; color: #c7d8ea !important; }",
    ".showcollapse_content a { color: #7dbdf2 !important; }",
    ".showcollapse_gather { color: #8099b2 !important; }",
    "/* === 甯栧瓙鍐呰仈楂樹寒 (瑕嗙洊 inline style) 寮哄埗娓呴櫎鍙戝笘浜鸿嚜甯﹀簳鑹?=== */",
    "font[color] { color: #c7d8ea !important; }",
    "font[color=\"#ff0000\" i], font[color=\"red\" i] { color: #ff6666 !important; }",
    "/* === 甯栧瓙搴曢儴鎿嶄綔鏍?(璇勫垎/鐐硅瘎)  & 鍒楄〃椤瑰簳閮ㄤ俊鎭?=== */",
    ".threadlist_foot { background: #182332 !important; border-color: #274766 !important; }",
    ".threadlist_foot a, .threadlist_foot i, .threadlist_foot em { color: #8099b2 !important; }",
    ".threadlist_foot li { border: 1px solid #4b6a8f !important; outline: none !important; box-shadow: none !important; }",
    ".threadlist_foot li.mr { border: none !important; }",
    ".threadlist_foot .dm-heart, .threadlist_foot .dm-chat-s, .dm-heart, .dm-chat-s, .dm-eye-fill, .dm-chat-s-fill { color: #8099b2 !important; }",
    "/* === 甯栧瓙鍒楄〃椤?- 椤堕儴 (澶村儚+鐢ㄦ埛鍚? === */",
    ".threadlist_top, .threadlist_top a, .threadlist_top .mimg, .threadlist_top .muser { background: #182332 !important; }",
    ".threadlist_top .mmc { color: #c7d8ea !important; }",
    ".threadlist_top .mtime { color: #6f89a3 !important; }",
    "/* === 甯栧瓙鍒楄〃椤?- 鏍囬&鎽樿 === */",
    ".threadlist_tit, .threadlist_tit em, .threadlist_tit a { background: #182332 !important; color: #edf4fb !important; }",
    ".threadlist_mes, .threadlist_mes a { background: #182332 !important; color: #95acc4 !important; }",
    "/* === 甯栧瓙闂村垎闅?=== */",
    ".discuz_x { background: #182332 !important; border-color: #274766 !important; }",
    "/* === 鍊掑簭/鍙湅妤间富 鏍?=== */",
    ".txtlist, .txtlist .mtit { background: #121b27 !important; color: #c7d8ea !important; border-color: #274766 !important; }",
    ".txtlist .ytxt, .txtlist a { color: #acbed1 !important; }",
    "/* === 甯栧瓙鍏冧俊鎭 === */",
    ".mtime, .mtime span, .mtime em, .mtime i { color: #8099b2 !important; }",
    ".y, .y span, .y em, .y i { color: #8099b2 !important; }",
    ".pstatus, .pstatus font { color: #8099b2 !important; }",
    "/* === 娴姩鑿滃崟 (鍥炲埌椤堕儴) === */",
    ".float-menu-item { background: rgba(51, 51, 51, 0.85) !important; color: #c7d8ea !important; }",
    ".float-menu-item svg { fill: #c7d8ea !important; color: #c7d8ea !important; }",
    ".scrolltop, #scrolltop, #scrolltop a { background: #274766 !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    "#mask { background: rgba(0,0,0,0.7) !important; }",
    "/* === 閫氱敤鏂囨湰瑕嗙洊 === */",
    "strong, b, .strong { color: #edf4fb !important; }",
    "sup, sub { color: #acbed1 !important; }",
    "em:not(#poll em) { color: #c7d8ea !important; }",
    ".display, .pi { background: #182332 !important; }",
    "/* === 淇澶滈棿妯″紡澶村儚琚?DOM 灞傚彔瑕嗙洊 === */",
    ".plc .avatar { z-index: 10 !important; background: transparent !important; }",
    ".plc .display, .plc .pi { background: transparent !important; }",
    "/* === 绛惧埌椤?(hui 妗嗘灦) === */",
    ".hui-header { background: #121b27 !important; }",
    ".hui-header h1 { color: #edf4fb !important; }",
    ".hui-slide-menu { background: #182332 !important; }",
    ".hui-slide-menu li { color: #c7d8ea !important; }",
    ".hui-wrap { background: #0d141d !important; }",
    ".hui-common-title-line { border-color: #274766 !important; }",
    ".hui-common-title-txt { color: #c7d8ea !important; }",
    ".hui-content { background: #182332 !important; color: #c7d8ea !important; }",
    ".hui-media-list li { background: #182332 !important; border-color: #274766 !important; }",
    ".hui-media-content { background: #182332 !important; }",
    ".hui-media-content p { color: #c7d8ea !important; }",
    ".hui-media-content a { color: #7dbdf2 !important; }",
    ".hui-list { background: #182332 !important; }",
    ".hui-list-text { color: #c7d8ea !important; }",
    ".hui-center-title h2 { color: #edf4fb !important; }",
    ".hui-button { background: #274766 !important; color: #c7d8ea !important; }",
    ".hui-primary { background: #4ea1ff !important; color: #fff !important; }",
    ".fl-table { background: #182332 !important; }",
    ".fl-table th { background: #1f2c3d !important; color: #c7d8ea !important; }",
    ".fl-table td { background: #182332 !important; color: #c7d8ea !important; }",
    ".day { color: #c7d8ea !important; }",
    ".day.today { background: #4ea1ff !important; color: #fff !important; }",
    ".lunar { color: #8099b2 !important; }",
    ".signbtn .btna { background: #4ea1ff !important; color: #fff !important; }",
    "/* === 鍙戝笘鏃堕棿/妤煎眰鍙?=== */",
    ".authi .mtit, .authi .mtime { color: #8099b2 !important; }",
    "/* === PhotoSwipe鎸夐挳 === */",
    ".pswp__button, .pswp__button:hover, .pswp__button:active { background: transparent !important; border-color: transparent !important; box-shadow: none !important; }",
    "/* === Portal / home page modules (use background-color only, never the */",
    "/* background shorthand, so inline background-image banners survive) === */",
    ".catenew, .catenew > .content, .listbox { background-color: #0d141d !important; }",
    ".listbox .module { background-color: #182332 !important; border-color: #274766 !important; }",
    ".listbox .module, .listbox .module li, .listbox .module p, .listbox .module .ytxt { color: #c7d8ea !important; }",
    ".listbox .tit, .listbox .tit h2 { background-color: #121b27 !important; color: #edf4fb !important; border-color: #274766 !important; }",
    ".listbox .module ul, .listbox .module li { background-color: #182332 !important; border-color: #223247 !important; }",
    "/* === Portal links: light blue, not brown === */",
    ".catenew a, .listbox a { color: #7dbdf2 !important; }",
    ".listbox .module em { color: #8099b2 !important; }",
    "/* === Portal / desktop index frames: dark border lines (carousel box, */",
    "/* hot-recommend box and other dividers keep light-theme borders otherwise) === */",
    ".catenew, .catenew .content, .imgbox, .listbox, .listbox .module, .listbox .tit, .catenew .slidebox, .catenew .frame, .catenew .block, .catenew .area, .catenew .column { border-color: #274766 !important; }",
    ".fl, .fl_g, .fl_icn, .bm_c, .frame, .area, .column, .block, .xl, .xl li, .el, .el li { border-color: #274766 !important; }",
    "/* === Top search bar === */",
    "#search_mid { background-color: #182332 !important; border-color: #274766 !important; }",
    "#scbar_type, #scbar_type.showmenu { color: #acbed1 !important; }",
    "#scbar_txt { background-color: #223247 !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    "#scbar_txt::placeholder { color: #8099b2 !important; }",
    "#scbar_btn { background-color: #274766 !important; border-color: #4b6a8f !important; }",
    "/* === Desktop Discuz fallback pages and profile pages === */",
    "#nv_forum, #nv_home, #nv_portal, .ct2, .ct3, .mn, .sd, #uhd, .h, .tns, .pf_l, .xld, .xlda, .ml, .buddy, .fl, .fl_tb, .fl_row, .fl_g, .fl_i, .fl_by, #chart, .chart, .ptm, .pbm, .mbm { color: #c7d8ea !important; }",
    ".ct2 a, .ct3 a, .mn a, .sd a, #uhd a, .h a, .tns a, .pf_l a, .xld a, .xlda a, .ml a, .buddy a, .fl a, .fl_tb a, .fl_row a, .fl_g a, .fl_i a, .fl_by a, #chart a, .chart a { color: #7dbdf2 !important; }",
    ".ct2 .xg1, .ct3 .xg1, .fl .xg1, .fl_i, .fl_by, .tns th, .tns td, .pf_l li, .xld dd, .xlda dd { color: #95acc4 !important; }",
    ".fl_tb, .fl_tb td, .fl_tb th, .fl_row, #uhd, .tns, .pf_l, .xld, .xlda { border-color: #274766 !important; }",
    "/* === Member DIY space pages (个人主页/日志/相册) are excluded from dark === */",
    "/* mode entirely - guarded in getDarkModeSetJs and proxyHtmlForDarkMode. === */",
    "/* === Desktop viewthread (body.pg_viewthread) === */",
    "/* Page-jump input on the right (第几页) stayed the light theme color. */",
    ".px, input.px, input.p_fre { background-color: #223247 !important; background-image: none !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    "/* Pagination action buttons (返回列表 / 发新帖 / 回复) were theme-brown. */",
    ".pgsbtn { background-color: #274766 !important; color: #c7d8ea !important; border-color: #4b6a8f !important; }",
    "/* Remaining brown text / links on the thread page -> readable on dark. */",
    ".pg_viewthread { color: #c7d8ea !important; }",
    ".pg_viewthread a { color: #7dbdf2 !important; }",
    ".pg_viewthread h1, .pg_viewthread .ts, .pg_viewthread .xst, .pg_viewthread .xi1 { color: #edf4fb !important; }",
    ".pg_viewthread .pg a, .pg_viewthread .pg .nxt, .pg_viewthread .pg .prev { color: #c7d8ea !important; }",
    ".pg_viewthread .pg strong { color: #ffffff !important; }",
    ".pg_viewthread .pgsbtn { color: #c7d8ea !important; }",
    "/* === Desktop viewthread containers === */",
    ".pg_viewthread #ct, .pg_viewthread #postlist, .pg_viewthread .pl, .pg_viewthread .plhin, .pg_viewthread .pct, .pg_viewthread .pcb, .pg_viewthread .t_fsz, .pg_viewthread .t_f { background: #182332 !important; border-color: #274766 !important; }",
    ".pg_viewthread .plc, .pg_viewthread .plm { background: #182332 !important; }",
    ".pg_viewthread .pls { background: #121b27 !important; border-color: #274766 !important; }",
    ".pg_viewthread .ad, .pg_viewthread .ad .plc, .pg_viewthread .ad .pls { background: #0d141d !important; border-color: #274766 !important; }",
    ".pg_viewthread .pls .avatar img { background: #1f2c3d !important; border-color: #3c5677 !important; box-shadow: 0 3px 5px rgba(0,0,0,0.45) !important; }",
    ".pg_viewthread #p_btn a, .pg_viewthread .locked, .pg_viewthread .showhide, .pg_viewthread .attach_nopermission, .pg_viewthread .attach_nopermission div { background: #1f2c3d !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    ".pg_viewthread .locked a, .pg_viewthread .attach_nopermission a, .pg_viewthread .showhide a { color: #7dbdf2 !important; }",
    ".pg_viewthread .locked-content { background: #1f2c3d !important; border-color: #3c5677 !important; }",
    ".pg_viewthread .locked-tip { background: #2a1b1f !important; color: #ff9a9a !important; border-color: #7a3f4b !important; }",
    ".pg_viewthread .tedt, .pg_viewthread .tedt .bar, .pg_viewthread .tedt .area, .pg_viewthread .m_c, .pg_viewthread .m_c .flb { background: #182332 !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    ".pg_viewthread #commentform .o, .pg_viewthread #viewui_fontsize li { background: #1f2c3d !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    ".pg_viewthread a[id^=postnum] { border-color: #274766 !important; }",
    ".pg_viewthread .psth .icon_ring, .pg_viewthread .ratl .xi1 { background: transparent !important; }",
    ".pg_viewthread .bui { box-shadow: 2px 2px 3px rgba(0,0,0,0.45) !important; }",
    "/* Poll / vote results: keep the colored bars (their colors come from inline */",
    "/* styles); only drop our dark panel boxing so the bars show cleanly. === */",
    "#poll table, #poll tbody, #poll tr, #poll td, #poll th, #poll .pcht { background: transparent !important; }",
    "/* 彩条轨道给一个微弱底色，深色背景下能看出每条的长度比例 */",
    "#poll .pbg { background: rgba(255,255,255,0.10) !important; }",
    "/* === 电脑版帖子页：楼层分隔线 / 各类衬线统一深蓝 === */",
    ".pg_viewthread #ct, .pg_viewthread #postlist, .pg_viewthread .pl, .pg_viewthread .pi, .pg_viewthread .pil, .pg_viewthread .pti, .pg_viewthread .po, .pg_viewthread .pob, .pg_viewthread .pdbt, .pg_viewthread .psth, .pg_viewthread .sign, .pg_viewthread .plc, .pg_viewthread .pls, .pg_viewthread .pct, .pg_viewthread .pcb, .pg_viewthread .plhin, .pg_viewthread .pm2, .pg_viewthread .tns, .pg_viewthread .tns th, .pg_viewthread .tns td, .pg_viewthread .t_fsz, .pg_viewthread .ad, .pg_viewthread .t_table, .pg_viewthread .t_table td, .pg_viewthread .p_tbl td, .pg_viewthread .cgtl td, .pg_viewthread .cgtl th, .pg_viewthread .cgtl caption { border-color: #274766 !important; }",
    "/* === 评分区（rate）=== */",
    ".rate, .ratc, .ratl, .ratl_l, .ratl th, .ratl td { background: #182332 !important; color: #c7d8ea !important; border-color: #274766 !important; }",
    ".rate a, .ratl a { color: #7dbdf2 !important; }",
    "/* === 点评 / 评论列表 === */",
    ".cmmnt, .cm, .psti { background: #1f2c3d !important; color: #c7d8ea !important; border-color: #274766 !important; }",
    ".cmmnt a, .cm a { color: #7dbdf2 !important; }",
    "/* === 悬浮提示气泡 / 用户信息卡片弹窗 === */",
    ".tip, .tip_c, .tip_4 { background: #182332 !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    ".p_pop.blk, .bui, .p_pop.blk.bui { background: #182332 !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    "/* === 弹窗对话框（fwin）=== */",
    ".fwin, .fwinmask .flb { background: #182332 !important; color: #c7d8ea !important; border-color: #3c5677 !important; }",
    "/* === 快速回复区 === */",
    ".fastre, #fastpost, .pgs.cl.mtm { background: #182332 !important; border-color: #274766 !important; }"
).map { rule ->
    // Keep site-supplied background images while changing only their backing color.
    rule.replace("background:", "background-color:")
}
